// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetMeResponse struct {
	Profile *User `json:"profile"`
}

type LoginInput struct {
	Name string `json:"name"`
}

type LoginResponse struct {
	AccessToken string `json:"accessToken"`
	Profile     *User  `json:"profile"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
