// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetMeResponse struct {
	Profile *Profile `json:"profile"`
}

type LoginInput struct {
	EmailOrUsername string `json:"emailOrUsername"`
	Password        string `json:"password"`
}

type LoginResponse struct {
	AccessToken string   `json:"accessToken"`
	Profile     *Profile `json:"profile"`
}

type Mutation struct {
}

type Profile struct {
	ID               int    `json:"id"`
	Username         string `json:"username"`
	Email            string `json:"email"`
	RegistrationDate string `json:"registration_date"`
	Verified         bool   `json:"verified"`
}

type Query struct {
}
